name: Build cnitool

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Build cnitool
      run: go build -o cnitool ./cnitool

    - name: Upload cnitool as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cnitool-artifact
        path: ./cnitool

